### PR TITLE
Update TableInput.tsx

### PR DESCRIPTION
**Pull request by alexgorgos**
"Error: Cannot resolve a Slate point from DOM point: [object Text]" issue fix

### CODE REVIEW

**Comment by davydog187** [comment]
Thanks @alexgorgos

**Comment by davydog187** [comment]
CI is failing, can you please take a look?

**Comment by kelenakamura** [comment]
is v1.0.3 going to get published to NPM?

**Comment by davydog187** [comment]
I've tried publishing but Sanity seems to have released breaking changes without respecting semver. @kelenakamura if you are interested in fixing and sending a PR, I'd be happy to publish a new version.

> npm publish
> 
> > @bitfo/sanity-plugin-portable-table@1.0.3 prepublishOnly
> > npm run build
> 
> 
> > @bitfo/sanity-plugin-portable-table@1.0.3 prebuild
> > npm run clean && plugin-kit verify-package --silent && pkg-utils
> 
> 
> > @bitfo/sanity-plugin-portable-table@1.0.3 clean
> > rimraf lib
> 
> node_modules/@sanity/types/lib/dts/src/index.d.ts:756:3 - error TS1139: Type parameter declaration expected.
> 
> 756   const TType extends string | IntrinsicTypeName, // IntrinsicTypeName here improves autocompletion in _some_ IDEs (not VS Code atm)
>       ~~~~~
> 
> node_modules/@sanity/types/lib/dts/src/index.d.ts:756:15 - error TS1005: ',' expected.
> 
> 756   const TType extends string | IntrinsicTypeName, // IntrinsicTypeName here improves autocompletion in _some_ IDEs (not VS Code atm)
>                   ~~~~~~~
> 
> node_modules/@sanity/types/lib/dts/src/index.d.ts:756:30 - error TS1005: ',' expected.
> 
> 756   const TType extends string | IntrinsicTypeName, // IntrinsicTypeName here improves autocompletion in _some_ IDEs (not VS Code atm)
>                                  ~
> 
> node_modules/@sanity/types/lib/dts/src/index.d.ts:757:3 - error TS1109: Expression expected.
> 
> 757   const TName extends string,
>       ~~~~~
> 
> node_modules/@sanity/types/lib/dts/src/index.d.ts:757:15 - error TS1005: ',' expected.
> 
> 757   const TName extends string,
>                   ~~~~~~~

**Pull request merged**
